name: Deploy Docusaurus Site

on:
  push:
    branches:
      - main  # Set this to the branch you use

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Bun
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo "$HOME/.bun/bin" >> $GITHUB_PATH
    - name: Configure Git
      run: |
        git config --global user.name "Clark Alesna"
        git config --global user.email "clark_alesna@hotmail.com"
    - name: Install dependencies
      run: bun install
    - name: Deploy to GitHub Pages
      env:
          GIT_PASS: ${{ secrets.GIT_PAT }}
          GIT_USER: mercurial
      run: bun run deploy
